### PR TITLE
Fix dependency in setup.py: `torch-nightly` has been renamed to `torch`

### PR DESCRIPTION
**Pull request by zasdfgbnm**
`torch-nightly` has been renamed to `torch`

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
This pull request **introduces 1 alert** when merging ce12de0967aaad5cf400e48cabe478c5791663c9 into 1455cb370dde0e8221d051cba14adf32ff28a59b - [view on LGTM.com](https://lgtm.com/projects/g/aiqm/torchani/rev/pr-5b54f3966221e731d73504f53bb1720358851c4c)

**new alerts:**

* 1 for Module is imported with &#39;import&#39; and &#39;import from&#39;

---

**Warning** - Automated code review for aiqm/torchani will be disabled on October 1, 2019. You can avoid this by <a href="https://github.com/apps/lgtm-com/installations/new">installing the LGTM.com GitHub App</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by zasdfgbnm** [comment]
This pull request **introduces 1 alert** when merging 4ea483fa50348510f51247b4f78044dcb4870772 into 1455cb370dde0e8221d051cba14adf32ff28a59b - [view on LGTM.com](https://lgtm.com/projects/g/aiqm/torchani/rev/pr-5327d64c8faf526fbf413aa79a03485e8cf6fd0d)

**new alerts:**

* 1 for Module is imported with &#39;import&#39; and &#39;import from&#39;

---

**Warning** - Automated code review for aiqm/torchani will be disabled on October 1, 2019. You can avoid this by <a href="https://github.com/apps/lgtm-com/installations/new">installing the LGTM.com GitHub App</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by zasdfgbnm** [comment]
Hi @farhadrgh, could you make a new release after this get merged? The dependency on `setup.py` has been changed from `torch-nightly` to `torch` because officially pytorch their package name. If we don't release, `pip install torchani` might fail due to `torch-nightly` not installed.

**Comment by farhadrgh** [comment]
> Hi @farhadrgh, could you make a new release after this get merged? The dependency on `setup.py` has been changed from `torch-nightly` to `torch` because officially pytorch their package name. If we don't release, `pip install torchani` might fail due to `torch-nightly` not installed.

yeah, sure, will release after this merged

**Pull request merged**
