### PR TITLE
ASE dropped python2 support

### PR DESCRIPTION
**Pull request by farhadrgh**
The [last version](https://pypi.org/project/ase/3.17.0/) that has python2 support will be installed for python2 tests.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
That is very strange. When I tried `pip2 install ase==3.17.0`, the first time it fails. Then it starts to success...

**Comment by isayev** [comment]
Since python2 is at EOL, it's probably a good idea to drop it.
However, we still QR friends that have extensive python2 legacy code :/

**Comment by zasdfgbnm** [comment]
@farhadrgh Could we also modify `install_dependencies.sh`, just temporarily, for now, to install an older version of ASE? This would unblock this PR.

**Comment by farhadrgh** [comment]
> @farhadrgh Could we also modify `install_dependencies.sh`, just temporarily, for now, to install an older version of ASE? This would unblock this PR.

Done!

**Pull request merged**
