### PR TITLE
Delete pad

### PR DESCRIPTION
**Pull request by IgnacioJPickering**
"pad" is a useless function now that ignite is gone.

### CODE REVIEW

**Comment by IgnacioJPickering** [comment]
So, I haven't modified the code in a while and it looks to me that many of the tests are failing and I have no idea why, is this normal? should these tests fail? I just deleted a function that is literally used nowhere in the code...
 what is deplot-test pypy? why is test_aev failing? makes no sense to me.

**Comment by zasdfgbnm** [comment]
It's not your fault

**Comment by zasdfgbnm** [comment]
The failure is weird. Let's just wait a few days to see if it gets fixed automatically

**Comment by zasdfgbnm** [comment]
@IgnacioJPickering Could you directly push to `aiqm/torchani`? GitHub secrets does not support PR from outside

**Pull request merged**
