### PR TITLE
bypass slow code

### PR DESCRIPTION
**Pull request by IgnacioJPickering**
I believe this still has issues so better not merge this at this point, I'm opening the PR to see if all tests pass, etc, since there are tests I'm too lazy to run

### CODE REVIEW

**Comment by IgnacioJPickering** [comment]
@zasdfgbnm @yueyericardo @farhadrgh This is failing AEV because it can't download something? how come?

```
HTTP request sent, awaiting response... 500 Internal Server Error
2020-02-27 23:05:13 ERROR 500: Internal Server Error.

  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
Archive:  download.zip
unzip:  cannot find zipfile directory in one of download.zip or
        download.zip.zip, and cannot find download.zip.ZIP, period.
##[error]Process completed with exit code 1.
```
???

**Comment by zasdfgbnm** [comment]
@IgnacioJPickering Yes, and just try rerun

**Comment by IgnacioJPickering** [comment]
@zasdfgbnm How do I do that? =/

**Comment by IgnacioJPickering** [comment]
empty commit?

**Comment by zasdfgbnm** [comment]
create an empty commit and push

**Comment by zasdfgbnm** [comment]
@IgnacioJPickering Is this still WIP?

**Comment by IgnacioJPickering** [comment]
@zasdfgbnm Yes, I've just been a bit lazy this week, I need to double check that the speed improvement is actually as good as I think it is since I had to do some extra changes since I did this
once I do that it will be fine I think.

**Comment by IgnacioJPickering** [comment]
@zasdfgbnm The size scaling improves a lot with this, but the improvement in training time is pretty crappy, about 2%, so I'm not sure we should merge it, I'll keep looking into it

**Comment by IgnacioJPickering** [comment]
@zasdfgbnm  @farhadrgh Further tests running a bunch of epochs imply improvement is actually 10-18 % so maybe it is significant =)

**Comment by zasdfgbnm** [comment]
@IgnacioJPickering That's good enough

**Comment by IgnacioJPickering** [comment]
Yes I think so, there are people here very interested in making this fast so I will keep on working on some of this stuff.

**Pull request merged**
