### PR TITLE
Add test for isolated atoms and large distances for 2 and 3 atoms

### PR DESCRIPTION
**Pull request by IgnacioJPickering**
## New test in test_aev
Currently there is a bug when an atom is isolated from its neighbors; when the neighbor list is empty 
AEVComputer crashes and raises IndexError. 
We had forgotten about this issue for a while so I made these tests that the current verision of torchani *fails*.

I made this to remind us that we have to fix this and to prevent this issue from arising again in the future.

Feedback is welcome!

### CODE REVIEW

**Comment by isayev** [comment]
From the software engineering it’s a bug, however currently no training was
done with isolated atoms. Systems like H2O, NH3 or CH4 were the smallest.
AEV descriptor is also ill-defied for diatomic molecules (H2, O2 etc).

**Comment by zasdfgbnm** [comment]
See: https://github.com/pytorch/pytorch/issues/22753

**Comment by zasdfgbnm** [comment]
It seems that this is not a TorchANI bug, but a PyTorch bug.
PS: `torch.repeat_interleave` was originally implemented by me. So I will look into that bug.

**Comment by zasdfgbnm** [comment]
@isayev Yes, agree.

**Comment by zasdfgbnm** [comment]
PyTorch fix: https://github.com/pytorch/pytorch/pull/23717

**Comment by IgnacioJPickering** [comment]
@isayev @zasdfgbnm I believe AEVs are, in principle, well defined for lone atoms or diatomics. For diatomics all the angular terms are automatically zero, and for lone atoms all radial and angular terms are automatically zero, so the AEV is just an array of zeros. I think this is built-in into the equations.

I agree that since no model has been trained to lone atoms the results are unpredictable, but in my opinion if we want to warn users when this happens a better solution is to print out a warning when the neighbohr lists are empty.

Wow, that fix was very fast thanks Xiang!

**Comment by zasdfgbnm** [comment]
@IgnacioJPickering I don't think we should warn the user about anything. There are much more than just empty neighbor list, for example, ANI currently could not do transition state well, also for things like bond breaking, excited electronic state might also need to be involved, etc. The user should know the limitation, not us warning on anything. I prefer the hole model being free of python stuff like exception handling because in the future we would need JIT to export our model and speed things up. These exceptions might become a hazard for JIT.

**Comment by zasdfgbnm** [comment]
reopening to see if pytorch update is on nightly

**Comment by IgnacioJPickering** [comment]
If this is a pytorch bug then maybe these tests are not the best because they look for an IndexError specifically. It is probably best to check that we get the correct AEV output for these molecules, same as what is done for benzeneMD, etc. If an IndexError or smth like that arises in the future the tests will fail anyways. Once pytorch nightly is updated we should probably rewrite this slightly

**Comment by IgnacioJPickering** [comment]
Also, I think python2 is failing because it exceeds the azure time limit =S

**Comment by zasdfgbnm** [comment]
But ASE should finish VERY FAST, as shown in: https://aiqm.github.io/torchani/examples/ase_interface.html

**Pull request merged**
