### PR TITLE
Added a yaml construct method for Trainer

### PR DESCRIPTION
**Pull request by stefdoerr**
I don't really know if you are interested in this. If not feel free to just close the PR. 
I just like config files in `yaml` as I find them more readable and they save you from defining a grammar or using lark.
Only thing it doesn't do is type check but I see that the lark definition is also quite flexible on the types.
I kept the lark parser in there just in case although this causes some obvious code duplication.

This is what the `yaml` file looks like although it's structure can be changed very easily.
https://gist.github.com/stefdoerr/47abc07538246a1b5026955453a83cdf

In the end I guess it's a personal taste issue so if you don't care for it or you didn't use yaml on purpose feel free to close this as I said :)

### CODE REVIEW

**Comment by stefdoerr** [comment]
Ok sure, then I will reformat the yaml parser to use the `_construct` method that already exists to avoid code duplication. I'll add the test tomorrow

**Comment by stefdoerr** [comment]
I think it's much cleaner now and works both with the lark config files and with yaml this way. I added a test but I'm not sure if you wanted it done this way.

**Comment by zasdfgbnm** [comment]
@stefdoerr Thanks a lot! LGTM now. But unfortunately I forget to turn on Azure pipeline build for pull requests. I will close and reopen this to see if it trigger the CI correct.

**Comment by zasdfgbnm** [comment]
@stefdoerr Could you please add `yaml` to https://github.com/aiqm/torchani/blob/master/azure/install_dependencies.sh#L5 ?

**Comment by stefdoerr** [comment]
How come the code coverage decreased? I added the test for azure, or does it not take this into account?

**Comment by zasdfgbnm** [comment]
@stefdoerr Just ignore the coverage, because the "test" for this part is not reported to coverage.

**Comment by zasdfgbnm** [comment]
@stefdoerr Thanks a lot for contribution!

**Pull request merged**
