### PR TITLE
Remove deprecated nonzero calls [WIP]

### PR DESCRIPTION
**Pull request by IgnacioJPickering**
The way we are calling nonzero in AEV computations is deprecated in the latest pytorch build

### CODE REVIEW

**Comment by IgnacioJPickering** [comment]
@zasdfgbnm calling without as_tuple is deprecated... but as_tuple is not jittable?

**Comment by zasdfgbnm** [comment]
Errr, that's bad. Maybe you can file an issue to PyTorch?

**Comment by IgnacioJPickering** [comment]
pytorch/pytorch#40601 I'll see what they say

**Comment by RMeli** [comment]
This appears to be the relevant PyTorch issue now: https://github.com/pytorch/pytorch/issues/45499

**Pull request closed without merging**
