### PR TITLE
[WIP] added files for dipole training

### PR DESCRIPTION
**Pull request by cdever01**
Added 2 files to examples: nnp_training_dipole.py and energy_force_dipole.py. 
nnp_training_dipole.py contains a class ANIModelDipole for training ANI models to predict dipoles and energies using an ACA model. The energy predictions contain a coulombic contribution. 
energy_force_dipole.py can be used to test models trained using nnp_training_dipole.py.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
@farhadrgh I think the reason why Christian is not triggering CI is because files inside `.github` is not configured well. A possible solution is to play with the `on` section: https://help.github.com/en/github/automating-your-workflow-with-github-actions/events-that-trigger-workflows#pull-request-event-pull_request

**Comment by farhadrgh** [comment]
> @farhadrgh I think the reason why Christian is not triggering CI is because files inside `.github` is not configured well. A possible solution is to play with the `on` section: https://help.github.com/en/github/automating-your-workflow-with-github-actions/events-that-trigger-workflows#pull-request-event-pull_request

#348 should fix this problem. I guess we haven't faced this since in all recent PRs we were pushing to base, instead of PR from a forked repo.

**Comment by IgnacioJPickering** [comment]
Should we close this for the moment?

**Comment by IgnacioJPickering** [comment]
I'm closing this since we should be merging work in progress like this into our private development repository, @cdever01 feel free to reopen this in our private repo.

**Pull request closed without merging**
